version: "3"

services:
  db:
    image: postgres
    container_name: db_service
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  get_data:
    build: .
    command: >
          sh -c "wait-for-it db:5432 -- &&
                python get_data.py"
    depends_on:
      - db

  print_data:
    build: .
    command: >
          sh -c "wait-for-it db:5432 -- &&
                python print_data.py"
    depends_on:
      - db
volumes:
    db_data:
        driver: local
